@app_url = localhost:8000
@users_endpoint = {{app_url}}/users
@orders_endpoint = {{app_url}}/orders

##### SENIORS
###
POST {{users_endpoint}}
Content-Type: application/json

< users/senior1.json

###
POST {{users_endpoint}}
Content-Type: application/json

< users/senior2.json

###
POST {{users_endpoint}}
Content-Type: application/json

< users/senior3.json

###
POST {{users_endpoint}}
Content-Type: application/json

< users/senior4.json

###
POST {{users_endpoint}}
Content-Type: application/json

< users/senior5.json

###
POST {{users_endpoint}}
Content-Type: application/json

< users/senior6.json

##### VOLUNTEERS

###
POST {{users_endpoint}}
Content-Type: application/json

< users/volunteer1.json

###
POST {{users_endpoint}}
Content-Type: application/json

< users/volunteer2.json

###
POST {{users_endpoint}}
Content-Type: application/json

< users/volunteer3.json

###
POST {{users_endpoint}}
Content-Type: application/json

< users/volunteer4.json

###
POST {{users_endpoint}}
Content-Type: application/json

< users/volunteer5.json

###
POST {{users_endpoint}}
Content-Type: application/json

< users/volunteer6.json

##### GROCERIES
###
POST {{orders_endpoint}}
Content-Type: application/json

< orders/groceries1.json

###
POST {{orders_endpoint}}
Content-Type: application/json

< orders/groceries1.json

###
POST {{orders_endpoint}}
Content-Type: application/json

< orders/groceries2.json

###
POST {{orders_endpoint}}
Content-Type: application/json

< orders/groceries3.json

###
POST {{orders_endpoint}}
Content-Type: application/json

< orders/groceries4.json
